name: ew_flutter_demo
description: "Flutter Demo for Embedded World"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.2
  import_sorter: ^4.6.0
  lottie: ^3.3.2
  very_good_analysis: ^10.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/lottie/
  fonts:
    - family: Inter
      fonts:
          - asset: assets/fonts/Inter.ttf
