name: Continuous Integration

on:
  workflow_dispatch:
  pull_request: {}
  push: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install cmake clang ninja-build pkg-config libgtk-3-dev -y -q

      - name: Run Flutter doctor
        run: flutter doctor

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Linux
        run: flutter build linux

      - name: Analyze code
        run: flutter analyze

      - name: Check formatting
        run: dart format lib --set-exit-if-changed

      - name: Check import sorting
        run: dart run import_sorter:main --exit-if-changed